// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/landing/VariantA.tsx": () => import("../components/mockups/landing/VariantA.tsx"),
  "./components/mockups/landing/VariantB.tsx": () => import("../components/mockups/landing/VariantB.tsx"),
  "./components/mockups/listlens-home/EvidenceLed.tsx": () => import("../components/mockups/listlens-home/EvidenceLed.tsx"),
  "./components/mockups/listlens-home/PersonaSplit.tsx": () => import("../components/mockups/listlens-home/PersonaSplit.tsx"),
  "./components/mockups/listlens-home/SpeedClaim.tsx": () => import("../components/mockups/listlens-home/SpeedClaim.tsx"),
  "./components/mockups/listlens-home/ToolFirst.tsx": () => import("../components/mockups/listlens-home/ToolFirst.tsx"),
  "./components/mockups/listlens-home/ToolFirstA.tsx": () => import("../components/mockups/listlens-home/ToolFirstA.tsx"),
  "./components/mockups/listlens-home/ToolFirstB.tsx": () => import("../components/mockups/listlens-home/ToolFirstB.tsx"),
  "./components/mockups/mobile/HomeV1.tsx": () => import("../components/mockups/mobile/HomeV1.tsx"),
  "./components/mockups/mobile/HomeV2.tsx": () => import("../components/mockups/mobile/HomeV2.tsx"),
  "./components/mockups/mobile/HomeV3.tsx": () => import("../components/mockups/mobile/HomeV3.tsx"),
  "./components/mockups/mobile/HomeV4.tsx": () => import("../components/mockups/mobile/HomeV4.tsx"),
  "./components/mockups/sole-lens/SoleLensLayoutA.tsx": () => import("../components/mockups/sole-lens/SoleLensLayoutA.tsx"),
  "./components/mockups/sole-lens/SoleLensLayoutB.tsx": () => import("../components/mockups/sole-lens/SoleLensLayoutB.tsx"),
  "./components/mockups/sole-lens/SoleLensLayoutC.tsx": () => import("../components/mockups/sole-lens/SoleLensLayoutC.tsx")
};
