// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/mobile/HomeV1.tsx": () => import("../components/mockups/mobile/HomeV1.tsx"),
  "./components/mockups/mobile/HomeV2.tsx": () => import("../components/mockups/mobile/HomeV2.tsx"),
  "./components/mockups/mobile/HomeV3.tsx": () => import("../components/mockups/mobile/HomeV3.tsx"),
  "./components/mockups/mobile/HomeV4.tsx": () => import("../components/mockups/mobile/HomeV4.tsx"),
  "./components/mockups/landing/VariantA.tsx": () => import("../components/mockups/landing/VariantA.tsx"),
  "./components/mockups/landing/VariantB.tsx": () => import("../components/mockups/landing/VariantB.tsx")
};
